extends: ["react-app", "plugin:@next/next/recommended"]
rules:
    {
        "array-bracket-spacing": 0,
        "arrow-parens": 0,
        "camelcase": 0,
        "comma-dangle": 0,
        "comma-spacing": 0,
        "computed-property-spacing": 0,
        "indent": 0,
        "key-spacing": 0,
        "max-statements-per-line": 0,
        "no-multi-spaces": 0,
        "no-underscore-dangle": 0,
        "no-unused-expressions": 0,
        "no-restricted-syntax": 0,
        "no-unused-vars": 0,
        "@typescript-eslint/no-unused-vars": 0,
        "one-var": 0,
        "operator-linebreak": 0,
        "space-before-function-paren": 0,
        "space-in-parens": 0,
        "valid-jsdoc": 0,
        "jsx-a11y/anchor-is-valid": 0,
    }
settings:
    react:
        version: "^17.0.2"
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 2020
    sourceType: "module"
env:
    jest: true
