# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 1

# Logger info
logging:
  level: trace
  streams:
    - type: stdout # log to stdout
      named_levels: true # emit log level name instead of index. e.g. INFO vs 30

# Using config.yaml with wikimedia service-runner pattern
services:
  - name: service-aletheia
    # path relative to the __dirname variable
    module: dist/server/seed.js
    conf:
      web_url: https://test.aletheiafact.org
      smtp_host: {env(SMTP_CLIENT_HOST)}
      smtp_port: {env(SMTP_CLIENT_PORT)}
      smtp_secure: true
      smtp_email_user: {env(SMTP_EMAIL_USER)}
      db:
        connection_uri: MONGODB_URI
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      users:
        - name: Test User
          email: test@aletheiafact.org
          password: TEST_USER_PASS
          sendAuthDetails: false
          isTestUser: true
          # Uncomment next line and provide Id if user already exists in Ory
          # oryId:
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
      novu:
        api_key: NOVU_API_KEY
        application_identifier: NOVU_APPLICATION_IDENTIFIER
