services:
  - name: ci-seed-command
    conf:
      disable_smtp: true
      db:
        connection_uri: {env(CI_MONGODB_URI)}
        type: mongodb
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      users:
        - name: Test User
          email: test-cypress@aletheiafact.org
          password: {env(CI_ORY_USER_PASSWORD)}
          sendAuthDetails: false
          isTestUser: true
          # If running locally and the seed fails, 
          # check the user's oryId at the link below. http://localhost:4434/admin/identities
          # oryId: {env(CI_ORY_USERID)}
          role: {
            main: super-admin
          }
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: http://localhost:4433
        admin_url: http://localhost:4434
        admin_endpoint: admin
        # url: {env(ORY_SDK_URL)}
        # access_token: {env(ORY_ACCESS_TOKEN)}
        # schema_id: {env(ALETHEIA_SCHEMA_ID)}
      feature_flag:
        url: {env(GITLAB_FEATURE_FLAG_URL)}
        appName: Staging
        instanceId: {env(GITLAB_FEATURE_FLAG_INSTANCE_ID)}
      openai:
        api_key: {env(OPENAI_API_KEY)}
      zenvia:
        api_url: {env(ZENVIA_API_URL)}
        api_token: {env(ZENVIA_API_TOKEN)}
