services:
  - name: service-aletheia
    conf:
      port: 3000
      cors: '*'
      debug: true
      websocketUrl: ws://localhost:5001
      agentsUrl: http://localhost:8000
      #override_public_routes: true
      recaptcha_secret: RECAPTCHA_SECRET
      recaptcha_sitekey: 6Lc2BtYUAAAAAOUBI-9r1sDJUIfG2nt6C43noOXh
      db:
        connection_uri: mongodb://localhost/Aletheia
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
      feature_flag:
        url: GITLAB_FEATURE_FLAG_URL
        appName: ENV
        instanceId: GITLAB_FEATURE_FLAG_INSTANCE_ID
      # example when using localstack
      aws:
        bucket: aletheia
        accessKeyId: test
        secretAccessKey: test
        # endpoint is only needed when using localstack
        endpoint: http://localhost:4566
      novu: # Notifications provider
        api_key: NOVU_API_KEY

