services:
  - name: ci-aletheia-server
    conf:
      port: 3000
      cors: '*'
      debug: true
      websocketUrl: ws://localhost:5001
      recaptcha_secret: {env(TEST_RECAPTCHA_SECRET)}
      recaptcha_sitekey: {env(TEST_RECAPTCHA_SITEKEY)}
      db:
        connection_uri: {env(CI_MONGODB_URI)}
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: {env(ORY_SDK_URL)}
        access_token: {env(ORY_ACCESS_TOKEN)}
        schema_id: {env(ALETHEIA_SCHEMA_ID)}
      feature_flag:
        url: {env(GITLAB_FEATURE_FLAG_URL)}
        appName: Staging
        instanceId: {env(GITLAB_FEATURE_FLAG_INSTANCE_ID)}
      aws:
        bucket: {env(AWS_SDK_BUCKET)}
        accessKeyId: {env(AWS_ACCESS_KEY_ID)}
        secretAccessKey: {env(AWS_SECRET_ACCESS_KEY)}
