services:
  - name: service-aletheia
    conf:
      port: 3000
      cors: '*'
      websocketUrl: wss://ws.aletheiafact.org
      recaptcha_secret: RECAPTCHA_SECRET
      recaptcha_sitekey: 6Lc2BtYUAAAAAOUBI-9r1sDJUIfG2nt6C43noOXh
      db:
        atlas: true
        connection_uri: MONGODB_URI
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      throttle:
        ttl: 60
        limit: 100
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
      feature_flag:
        url: GITLAB_FEATURE_FLAG_URL
        appName: ENV
        instanceId: GITLAB_FEATURE_FLAG_INSTANCE_ID
      aws:
        bucket: AWS_SDK_BUCKET
        accessKeyId: AWS_ACCESS_KEY_ID
        secretAccessKey: AWS_SECRET_ACCESS_KEY
      novu: # Notifications provider
        api_key: NOVU_API_KEY
        application_identifier: NOVU_APPLICATION_IDENTIFIER
