services:
  - name: service-aletheia
    conf:
      web_url: https://test.aletheiafact.org
      smtp_host: {env(SMTP_CLIENT_HOST)}
      smtp_port: {env(SMTP_CLIENT_PORT)}
      smtp_secure: true
      smtp_email_user: {env(SMTP_EMAIL_USER)}
      db:
        connection_uri: MONGODB_URI
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      users:
        - name: Test User
          email: test@aletheiafact.org
          password: TEST_USER_PASS
          sendAuthDetails: false
          isTestUser: true
          # Uncomment next line and provide Id if user already exists in Ory
          # oryId:
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        admin_url: ORY_SDK_URL
        # Use "admin" as the endpoint when running locally.
        # When using the cloud, the endpoint should be "api/kratos/admin".
        admin_endpoint:
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
