# Number of worker processes to spawn.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 1

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
# worker_heap_limit_mb: 250

# Logger info
logging:
  level: trace
  streams:
  - type: stdout # log to stdout
    named_levels: true # emit log level name instead of index. e.g. INFO vs 30

# Using config.yaml with wikimedia service-runner pattern
services:
  - name: service-aletheia
    # path relative to the __dirname variable
    module: dist/server/main.js
    conf:
      port: 3000
      cors: '*'
      debug: true
      #override_public_routes: true
      recaptcha_secret: RECAPTCHA_SECRET
      recaptcha_sitekey: 6Lc2BtYUAAAAAOUBI-9r1sDJUIfG2nt6C43noOXh
      db:
        connection_uri: mongodb://localhost/Aletheia
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
      feature_flag:
        url: GITLAB_FEATURE_FLAG_URL
        appName: ENV
        instanceId: GITLAB_FEATURE_FLAG_INSTANCE_ID
      # example when using localstack
      aws:
        bucket: aletheia
        accessKeyId: test
        secretAccessKey: test
        # endpoint is only needed when using localstack
        endpoint: http://localhost:4566
