services:
  - name: service-aletheia
    conf:
      app_affiliation: aletheia
      port: 3000
      cors: "*"
      debug: true
      websocketUrl: ws://localhost:5001
      baseUrl: "http://localhost:3000"
      automatedFactCheckingAPIUrl: AGENTS_API_URL
      #override_public_routes: true
      recaptcha_secret: RECAPTCHA_SECRET
      recaptcha_sitekey: 6Lc2BtYUAAAAAOUBI-9r1sDJUIfG2nt6C43noOXh
      db:
        connection_uri: mongodb://localhost/Aletheia
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        # Use "admin" as the endpoint when running locally.
        # When using the cloud, the endpoint should be "api/kratos/admin".
        admin_endpoint:
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
        hydra:
          url: ORY_SDK_URL
          # When using the cloud, the endpoint should be "admin".
          admin_endpoint:
      feature_flag:
        url: GITLAB_FEATURE_FLAG_URL
        appName: ENV
        instanceId: GITLAB_FEATURE_FLAG_INSTANCE_ID
      # example when using localstack
      aws:
        bucket: aletheia
        accessKeyId: test
        secretAccessKey: test
        # endpoint is only needed when using localstack
        endpoint: http://localhost:4566
      novu: # Notifications provider
        api_key: NOVU_API_KEY
      openai:
        api_key: OPENAI_API_KEY
      zenvia:
        api_url: ZENVIA_API_URL
        api_token: ZENVIA_API_TOKEN
      agencia:
        access_token: AGENCIA_ACCESS_TOKEN
