apiVersion: v1
kind: ConfigMap
metadata:
  name: aletheia-config
  namespace: development
data:
  api_url: https://test.aletheiafact.org/api
  mongodb_host: 10.128.0.5
  mongodb_name: development
  recaptcha_sitekey: 6Lc2BtYUAAAAAOUBI-9r1sDJUIfG2nt6C43noOXh
  next_public_umami_site_id: e2160466-7450-433e-b486-338adaf2e532
  ory_sdk_url: https://trusting-clarke-6bsip5gwko.projects.oryapis.com
  ory_access_token: ory_pat_4uZoC4gOd4RPx3gPjR2i5ZgglsHSnRTx
