# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 2

# Number of workers to start in parallel after the first worker.
# The first worker is always started independently. After it has completed
# its start-up, this number controls the number of workers to start in
# parallel until `num_workers` have been started. Note that setting this
# number to a too high a value might lead to high resource consumption
# (especially of CPU) during the start-up process.
startup_concurrency: 1

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
worker_heap_limit_mb: 750

# The maximum interval in ms that can pass between two beat messages
# sent by each worker to the master before it is killed
worker_heartbeat_timeout: 15000

# Logger info
logging:
  level: trace
  streams:
  - type: stdout # log to stdout
    named_levels: true # emit log level name instead of index. e.g. INFO vs 30

# Using config.yaml with wikimedia service-runner pattern
services:
  - name: service-aletheia
    # path relative to the __dirname variable
    module: dist/server/main.js
    conf:
      port: 3000
      cors: '*'
      debug: true
      websocketUrl: ws://test.ws.aletheiafact.org
      override_public_routes: true
      recaptcha_secret: RECAPTCHA_SECRET
      recaptcha_sitekey: 6Lc2BtYUAAAAAOUBI-9r1sDJUIfG2nt6C43noOXh
      db:
        connection_uri: MONGODB_URI
        atlas: true
        options:
          useUnifiedTopology: true
          useNewUrlParser: true
          retryWrites: true
          w: majority
      throttle:
        ttl: 60
        limit: 1000
      authentication_type: ory
      ory:
        url: ORY_SDK_URL
        access_token: ORY_ACCESS_TOKEN
        schema_id: ALETHEIA_SCHEMA_ID
      feature_flag:
        url: GITLAB_FEATURE_FLAG_URL
        appName: ENV
        instanceId: GITLAB_FEATURE_FLAG_INSTANCE_ID
      aws:
        bucket: AWS_SDK_BUCKET
        accessKeyId: AWS_ACCESS_KEY_ID
        secretAccessKey: AWS_SECRET_ACCESS_KEY
