# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 1

# Logger info
logging:
  level: trace
  streams:
    - type: stdout # log to stdout
      named_levels: true # emit log level name instead of index. e.g. INFO vs 30

# Using config.yaml with wikimedia service-runner pattern
services:
  - name: service-aletheia
    # path relative to the __dirname variable
    module: dist/server/seed.js
    conf:
      web_url: https://test.aletheiafact.org
      smtp_host: SMTP_HOST
      smtp_port: SMTP_PORT
      smtp_secure: false
      smtp_email_user: SMTP_EMAIL_USER
      smtp_email_pass: SMTP_EMAIL_PASS
      users:
        - name: Test User
          email: test@aletheiafact.org
          sendAuthDetails: false
          isTestUser: true
