@startuml claimCreatePage
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 150
skinparam sequenceParticipant underline

!theme mars
title Claim Create Page\n\npersonality/:slug/claim/create/

actor User
participant "Claim Controller" as A
participant "Personality Service" as B
participant "Claim Revision Service" as C
database "MongoDB" as D

User -> A ++: //Request create claim page// :claimCreatePage()

note right
  receive personalitySlug
  from the endpoint of the URL
end note

A -> A: //Indentify Language//
||15||
A -> B ++: //get personality by the personality slug of the endpoint//\n:getBySlug(\nreq.params.slug, req.language\n)
||15||
B ->> D ++: //find personality by the slug//
||15||
D -->> B --: //return personality//
||15||
B ->> C ++: //for each claim in personality// :getRevision(claim.id)
||15||
C -->> B --: //return lastest claim revisions//
||15||
B ->> B: //return claim revisions as object//
||15||
B ->> B: //if is enabled isAllowedProp enjoy wikidata API// :postProcess(personality)
||15||
B --> A --: return personality
||15||
A -->> User --: Response create claim page
@enduml