@startuml getSenteceReviewsByHash
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 150
skinparam sequenceParticipant underline

!theme mars
title Claim Reviews Page\n\napi/claim/:claimId/sentence/:sentenceHash/reviews

actor User
participant "Claim Controller" as A
participant "Claim Service" as B
database "MongoDB" as C

User -> A ++: //Request claims reviews// :getClaimsByHashDTO()

alt
  note right
    receive sentenceHash from
    the endpoint of the URL and
    the other params from Request
  end note
  A -> A: //indentify language//\n:get()
  A ->> B ++: :getReviewsBySentenceHash(\nsentenceHash, page, pageSize, order\n) 
else
  A --> User: //Internal server error//
  note right
      async function
  end note

B -> C ++: //get claim reviews//
||15||
C -->> B --: //return claim reviews//
||15||
A ->> B: //count all claim reviews// :countReviewsBySentenceHash(\nsentenceHash\n) 
||15||
B -->> B: //return total claim reviews//
||15||
B --> A --: //return claim reviews formated//
||15||
A --> User --: //Response is returned to the client//
@enduml
