@startuml listAllClaims
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 150
skinparam sequenceParticipant underline

!theme mars
title Claim Page

actor User
participant "Claim Controller" as A
participant "Claim Service" as B
database "MongoDB" as C

User -> A ++: //Request claims// :getClaimsDTO()

note right
  receive params from Request
end note

alt
  A -> A: //indentify language// :get()
else
  A --> User: Internal server error

A -> B ++: :listAll(page, pageSize, order, query)
||15||
B -> C ++: get all claim revisions by query
||15||
C --> B --: return claim revisions
||15||
B ->> B: return claim revisions as object
||15||
B --> A --: create claim response
||15||
A --> User --: Response is returned to the client
@enduml
