components:
  parameters:
    personalityId:
      in: path
      name: id
      required: true
      schema:
        type: string
      description: |
        Personality's ID
    claimId:
      in: path
      name: id
      required: true
      schema:
        type: string
      description: |
        Claim's ID