export const users = [{
    id: 1,
    first_name: "Giffy",
    last_name: "Crookall",
    email: "gcrookall0@dmoz.org",
    gender: "Male"
}, {
    id: 2,
    first_name: "Dolli",
    last_name: "Pochet",
    email: "dpochet1@paginegialle.it",
    gender: "Female"
}, {
    id: 3,
    first_name: "Esmaria",
    last_name: "Tysall",
    email: "etysall2@mashable.com",
    gender: "Female"
}, {
    id: 4,
    first_name: "Brice",
    last_name: "Cleynman",
    email: "bcleynman3@census.gov",
    gender: "Male"
}, {
    id: 5,
    first_name: "Laureen",
    last_name: "Benzies",
    email: "lbenzies4@opensource.org",
    gender: "Female"
}, {
    id: 6,
    first_name: "Lock",
    last_name: "Heigl",
    email: "lheigl5@chron.com",
    gender: "Male"
}, {
    id: 7,
    first_name: "Raoul",
    last_name: "Poland",
    email: "rpoland6@1688.com",
    gender: "Male"
}, {
    id: 8,
    first_name: "Seymour",
    last_name: "Schutze",
    email: "sschutze7@bigcartel.com",
    gender: "Male"
}, {
    id: 9,
    first_name: "Mylo",
    last_name: "Zapater",
    email: "mzapater8@admin.ch",
    gender: "Male"
}, {
    id: 10,
    first_name: "Jodee",
    last_name: "Halleybone",
    email: "jhalleybone9@360.cn",
    gender: "Female"
}]